# Site config
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koppts.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Meta Info
title: Short title
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
avatar: #assets/img/avatar.jpg
favicon: #assets/favicon.ico

# Header and footer text
header_text: It's a nerds world
header_feature_image: assets/img/pc_hardware.jpg
footer_text: >
  A loose collection of thoughts around computer and nerd topics 

# Theme config
remote-theme: sylhare/Type-on-Strap
plugins:
  - jekyll-feed

# Blog
excerpt: truncate
post_navigation: true
color_image: /assets/img/lineart.png 

color_image: #/assets/img/lineart.png # In post when you set color

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# Excludes
exclude:
  - README.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
