# Site config
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koppts.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Meta Info
title: It's a nerds world
description: #todo add desc

color_theme: auto

defaults:
  - scope:
      path: "" # an empty string here means all necessary files are in the project
    values:
      image: #assets/img/

# THEME-SPECIFIC CONFIGURATION
theme_settings:

  avatar: assets/img/aurora.jpg
  favicon: #assets/favicon.ico

  # Header and footer text
  header_text: It's a nerds world
  header_feature_image: assets/img/pc_hardware.jpeg
  footer_text: >
    A loose collection of thoughts around computer and nerd topics 
  
  # Theme config
  remote-theme: sylhare/Type-on-Strap
  
  # Blog
  excerpt: false
  post_navigation: true
  color_image: /assets/img/lineart.png
  
  # PAGINATION
  paginate: 10
  paginate_path: "/blog/page:num"
  
  katex: true
  mermaid: true
  
  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: 
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit: 
  soundcloud:
  stack_overflow:
  stack_exchange:  # Full URL
  steam: 
  tumblr:
  twitter: "koppts"
  vimeo:
  wordpress:
  youtube:

  share_buttons:
      facebook: 
      twitter: true
      tumblr:
      pinterest:
      pocket: true
      reddit: 
      linkedin:
      wordpress:
      email: true
  
  # PORTFOLIO
  collections:
    portfolio:
      output: true
      permalink: /:collection/:name

authors:
  koppts: # author-id
    name: "Thomas Kopp"
    avatar: "assets/img/aurora.jpg"
    url: https://twitter.com/koppts


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
